stages:
  - test
  - deploy

code_quality:
  image: node:16.16.0
  stage: test
  before_script:
    - npm ci
  script:
    - npm run eslint
    - npm run stylelint
    - npm run prettier-check
  only:
    - merge_requests

test:
  image: node:16.16.0
  stage: test
  before_script:
    - npm ci
  script:
    - npm run test
  only:
    - master

cypress_test:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - npm ci
    - npm run start &
    - npx cypress run
  only:
    - master

pages:
  image: node:16.16.0
  stage: deploy
  before_script:
    - npm install
  script:
    - npm run build
    - cp -r dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
